### ISSUE TITLE
Container start error "mail"

### ISSUE THREAD

**Issue by MarcusFloeser** [nextBOSS-Capabilities/openldap-mailcow#2]
I got a start error in py script .. where can I search for the issue?
`mailcowcustomized_ldap-mailcow  | 24.03.23 09:35:11 Config file conf/dovecot/ldap/passdb.conf unchanged
mailcowcustomized_ldap-mailcow  | 24.03.23 09:35:11 Config file conf/dovecot/extra.conf unchanged
mailcowcustomized_ldap-mailcow  | 24.03.23 09:35:11 Config file conf/sogo/plist_ldap unchanged
mailcowcustomized_ldap-mailcow  | Traceback (most recent call last):
mailcowcustomized_ldap-mailcow  |   File "//syncer.py", line 186, in <module>
mailcowcustomized_ldap-mailcow  |     main()
mailcowcustomized_ldap-mailcow  |   File "//syncer.py", line 31, in main
mailcowcustomized_ldap-mailcow  |     sync()
mailcowcustomized_ldap-mailcow  |   File "//syncer.py", line 55, in sync
mailcowcustomized_ldap-mailcow  |     for (email, ldap_name, ldap_active) in ldap_results:
mailcowcustomized_ldap-mailcow  |   File "//syncer.py", line 47, in <lambda>
mailcowcustomized_ldap-mailcow  |     x[1]['mail'][0].decode(),
mailcowcustomized_ldap-mailcow  |     ~~~~^^^^^^^^
mailcowcustomized_ldap-mailcow  | KeyError: 'mail'
`

**Comment by MarcusFloeser** [comment]
ok, issue found. There was a wrong LDAP filter.

**Comment by l4b4r4b4b4** [comment]
hmmm it was working for me no prob. Can you point me to wrong filter or simply make a pull req.!

Would be lovely ;)

**Comment by MarcusFloeser** [comment]
I meant I set a filter in docker-compose.override.yml

**Comment by l4b4r4b4b4** [comment]
ah so the LDAP filter you set as environment variable was wrong you mean? Writing from Germany as well btw? :smile:

**Comment by MarcusFloeser** [comment]
Ah ok, das macht es einfacher .. in german :-)

Wie auch immer, das Log sagt mir nun alles ok, die Accounts werden gesynct. Und er hat auch schon eine neue Mailbox angelegt in mailcow. Aber ich kann mich nicht anmelden an der mailbox in SOGo

**Comment by l4b4r4b4b4** [comment]
ja der Name war doch sehr sprechend. 
SoGo sollte eigentlich funktionieren ;)
Allerdings: SoGO Login für LDAP Konten funktioniert mit dem Nutzernamen nicht mit der kompletten E-Mail. 
Wenn du weitere Fragen hast, schreib mir doch am Besten auf Discord unter `LHC#1921`.

**Comment by l4b4r4b4b4** [comment]
Solvable with correct template settings!
